# Permalinks
permalink:        pretty

# Setup
title:            Relojban
tagline:          'A machine-parsable constructed language based on Lojban'
description:      'A machine-parsable constructed language based on Lojban'
url:              http://relojban.github.io
baseurl:          /

# Custom vars
github:
  repo: https://github.com/relojban/
